CREATE TABLE images (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT,
  image_url TEXT,
  image_width INTEGER,
  image_height INTEGER,
  experiment_id INTEGER REFERENCES experiments(id) NOT NULL ON DELETE CASCADE
);